# Generated by Django 3.0.1 on 2019-12-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioIdade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relatório por Idade',
                'verbose_name_plural': 'Relatório por Idades',
                'db_table': 'relatorio_idade',
            },
        ),
        migrations.CreateModel(
            name='RelatorioIdadeEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relatório por Idade Especifico',
                'verbose_name_plural': 'Relatório por Idades Especificas',
                'db_table': 'relatorio_idade_especifico',
            },
        ),
        migrations.CreateModel(
            name='RelatorioStatusPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relatório Status Pagamento',
                'verbose_name_plural': 'Relatório Status Pagamento',
                'db_table': 'relatorio_status_pag',
            },
        ),
    ]
