# Generated by Django 3.0.3 on 2020-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_relatorioidade_relatorioidadeespecifico_relatoriostatuspagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioHospedagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relatório por Hospedagem',
                'verbose_name_plural': 'Relatório por Hospedagem',
                'db_table': 'relatorio_hospedagem',
            },
        ),
    ]
