# Generated by Django 2.2.6 on 2019-12-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cpf',
            field=models.CharField(default=None, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
