# Generated by Django 2.2.6 on 2019-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='data_nascimento',
            field=models.DateField(default=None, null=True, verbose_name='Data Nascimento'),
        ),
    ]
