# Generated by Django 3.0.1 on 2020-01-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    def corrigir_username(apps, schema_editor):
        Account = apps.get_model('accounts', 'Account')
        for account in Account.objects.all():
            if account.username is None or account.username == '':
                account.username = account.email
                account.save()

    dependencies = [
        ('accounts', '0002_account_tp_user_financeiro'),
    ]

    operations = [
        migrations.RunPython(corrigir_username),
    ]
