# Generated by Django 3.0.1 on 2020-01-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200111_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telefone',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Telefone'),
        ),
    ]
