version: '3'

volumes:
  data:

services:
  db:
    image: postgres:10
    volumes:
    - ./db/:/db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inscricao
    ports:
      - 5432:5432
  # mysql:
  #   image: mysql:5.6
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_USER=root
  #     - MYSQL_DATABASE=inscricao
  app:
    build: ./
    command: >
        bash -c "pip install -r requirements.txt 
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    links:
      - db
    depends_on:
      - db