# Generated by Django 3.0.3 on 2020-03-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregacao',
            name='arquivos',
        ),
    ]
