# Generated by Django 3.0.1 on 2019-12-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_receitas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receitas',
            options={'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AddField(
            model_name='receitas',
            name='data_receita',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Receita'),
        ),
    ]
