# Generated by Django 3.0.1 on 2020-01-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20200106_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitação'), (2, 'Aprovada'), (3, 'Recurso Repassado'), (4, 'Aguardando Comprovação'), (5, 'Comprovação em Analise'), (6, 'Comprovado')], default=1, verbose_name='Status'),
        ),
    ]
