# Generated by Django 3.0.1 on 2020-01-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20200111_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Solicitação'),
        ),
    ]
