# Generated by Django 3.0.1 on 2020-01-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_despesas_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='justificativa_reprovacao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Justificativa Reprovação'),
        ),
        migrations.AddField(
            model_name='despesas',
            name='reprovado',
            field=models.BooleanField(default=False, verbose_name='Reprovado?'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitação'), (2, 'Aprovada'), (3, 'Recurso Repassado'), (4, 'Aguardando Comprovação'), (5, 'Comprovação em Analise'), (6, 'Comprovado'), (8, 'Reprovado')], default=1, verbose_name='Status'),
        ),
    ]
