# Generated by Django 3.0.1 on 2020-01-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_auto_20200115_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
                ('data_comprovação', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Comprovação')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.Despesas', verbose_name='Despesa')),
            ],
            options={
                'verbose_name': 'Comprovante Despesa',
                'verbose_name_plural': 'Comprovantes Despesa',
                'db_table': 'comprovantes_despesa',
            },
        ),
    ]
