# Generated by Django 3.0.3 on 2020-02-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_remove_despesas_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovantes',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Despesas', verbose_name='Despesa'),
        ),
    ]
