# Generated by Django 3.0.8 on 2020-07-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portal_colunacmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('coluna', models.CharField(choices=[['1', '1 Coluna'], ['2', '2 Colunas'], ['4', '4 Colunas'], ['6', '6 Colunas'], ['8', '8 Colunas'], ['10', '10 Colunas'], ['12', '12 Colunas']], max_length=10, verbose_name='Coluna')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
