# Generated by Django 3.0.8 on 2020-07-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('portal', '0002_titulopaginacmsplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloComponenteCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portal_titulocomponentecmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='colunacmsplugin',
            name='coluna',
            field=models.CharField(choices=[['col-sm-12', '1 Coluna'], ['col-sm-6', '2 Colunas'], ['col-sm-4', '3 Colunas'], ['col-sm-3', '4 Colunas'], ['col-sm-2', '6 Colunas']], max_length=50, verbose_name='Coluna'),
        ),
    ]
