# Generated by Django 3.0.8 on 2020-07-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('portal', '0003_auto_20200719_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoComponenteCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portal_textocomponentecmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('texto', models.TextField(verbose_name='Texto')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TituloH3ComponenteCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portal_tituloh3componentecmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
