# Generated by Django 3.0.1 on 2019-12-23 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo do Evento', max_length=80, verbose_name='Titulo')),
                ('titulo_slug', models.SlugField(help_text='Esse campo é o codigo unico da conferencia, não alterar esse campo', unique=True, verbose_name='Slug')),
                ('max_inscr', models.IntegerField(default=500000, verbose_name='Maximo inscrições')),
                ('data_abertura', models.DateTimeField(verbose_name='Data Abertura Inscrições')),
                ('data_encerramento', models.DateTimeField(verbose_name='Data Encerramento Inscrições')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(blank=True, max_length=320, verbose_name='Endereço (googlemaps)')),
                ('informacoes', models.TextField(blank=True, verbose_name='Informações Gerais')),
                ('inscricoes_abertas', models.BooleanField(default=True, verbose_name='Inscrições Abertas?')),
                ('informacoes_arquivo', models.FileField(blank=True, null=True, upload_to='informacoes/arquivos/', verbose_name='Arquivo de Informações')),
            ],
            options={
                'verbose_name': 'Conferencia',
                'verbose_name_plural': 'Conferencias',
                'db_table': 'conferencia',
            },
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome Hospedagem')),
                ('limite', models.IntegerField(default=0, verbose_name='Limite de Hospedes')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Conferencia', verbose_name='Conferência')),
            ],
            options={
                'verbose_name': 'Hospedagem Conferência',
                'verbose_name_plural': 'Hospedagem Conferência',
                'db_table': 'hospedagem_conferencia',
            },
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_inicial', models.IntegerField(default=0, verbose_name='Idade Inicial')),
                ('idade_final', models.IntegerField(default=120, verbose_name='Idade Final')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Inscrição')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Conferencia', verbose_name='Conferência')),
            ],
            options={
                'verbose_name': 'Valor Inscrição Conferencia',
                'verbose_name_plural': 'Valores Inscrição Conferencia',
                'db_table': 'valor_inscricao_conferencia',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nome_cracha', models.CharField(blank=True, max_length=100, verbose_name='Nome Crachá')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=60, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('ddd', models.CharField(max_length=3, verbose_name='DDD')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('observacoes', models.CharField(blank=True, max_length=400, verbose_name='Observações')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Inscrição')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total Inscrição')),
                ('idade', models.IntegerField(default=0, verbose_name='Idade')),
                ('pagseguro_code', models.CharField(blank=True, max_length=120, verbose_name='Token PagSeguro')),
                ('payment_reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia Pagamento')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Pago'), (3, 'Cancelado'), (4, 'Aguardando Confirmação Pagamento')], default=1, verbose_name='Status')),
                ('sit_pagseguro', models.IntegerField(blank=True, null=True, verbose_name='Status PagSeguro')),
                ('pagseguro_transaction_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='Transação PagSeguro')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Conferencia', verbose_name='Conferência')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Hospedagem', verbose_name='Hospedagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricao',
                'unique_together': {('conferencia', 'cpf')},
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('grau', models.IntegerField(choices=[(1, 'Conjugue'), (2, 'Filho(a)'), (3, 'Pai/Mãe'), (4, 'Outro')], verbose_name='Grau Parentesco')),
                ('nome_cracha', models.CharField(blank=True, max_length=100, verbose_name='Nome Crachá')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('idade', models.IntegerField(default=0, verbose_name='Idade')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Inscrição')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'db_table': 'dependente',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('assunto', models.CharField(max_length=120, verbose_name='Assunto')),
                ('data_contato', models.DateTimeField(auto_now_add=True, verbose_name='Data Contato')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Conferencia', verbose_name='Conferência')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contato',
            },
        ),
    ]
