# Generated by Django 2.2.6 on 2019-12-03 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Titulo')),
                ('max_inscr', models.IntegerField(default=500000, verbose_name='Maximo inscrições')),
                ('data_abertura', models.DateTimeField(verbose_name='Data Abertura Inscrições')),
                ('data_encerramento', models.DateTimeField(verbose_name='Data Encerramento Inscrições')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conferencia',
                'verbose_name_plural': 'Conferencias',
                'db_table': 'conferencia',
            },
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=9, verbose_name='Nome Hospedagem')),
                ('limite', models.IntegerField(default=0, verbose_name='Limite de Hospedes')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Conferencia', verbose_name='Conferência')),
            ],
            options={
                'verbose_name': 'Hospedagem Conferência',
                'verbose_name_plural': 'Hospedagem Conferência',
                'db_table': 'hospedagem_conferencia',
            },
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_inicial', models.IntegerField(default=0, verbose_name='Idade Inicial')),
                ('idade_final', models.IntegerField(default=120, verbose_name='Idade Final')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Inscrição')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Conferencia', verbose_name='Conferência')),
            ],
            options={
                'verbose_name': 'Valor Inscrição Conferencia',
                'verbose_name_plural': 'Valores Inscrição Conferencia',
                'db_table': 'valor_inscricao_conferencia',
            },
        ),
        migrations.CreateModel(
            name='inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nome_cracha', models.CharField(max_length=100, verbose_name='Nome Crachá')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=60, verbose_name='Numero')),
                ('complemento', models.CharField(max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('ddd', models.CharField(max_length=3, verbose_name='DDD')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('observacoes', models.CharField(max_length=400, verbose_name='Observações')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inscrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Inscrição')),
                ('idade', models.IntegerField(default=0, max_length=10, verbose_name='Idade')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Conferencia', verbose_name='Conferência')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Hospedagem', verbose_name='Hospedagem')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricao',
                'unique_together': {('conferencia', 'cpf')},
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('grau', models.CharField(choices=[(1, 'Conjugue'), (2, 'Filho(a)'), (3, 'Pai/Mãe'), (4, 'Outro')], max_length=30, verbose_name='Grau Parentesco')),
                ('nome_cracha', models.CharField(max_length=100, verbose_name='Nome Crachá')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('idade', models.IntegerField(default=0, max_length=10, verbose_name='Idade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inscrição')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'db_table': 'dependente',
            },
        ),
    ]
