# Generated by Django 3.0.1 on 2020-02-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='conferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Conferencia', verbose_name='Conferência'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='hospedagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Hospedagem', verbose_name='Hospedagem'),
        ),
    ]
