# Generated by Django 2.2.6 on 2019-12-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='idade',
            field=models.IntegerField(default=0, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='idade',
            field=models.IntegerField(default=0, verbose_name='Idade'),
        ),
    ]
