# Generated by Django 2.2.6 on 2019-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='titulo',
            field=models.CharField(help_text='Titulo do Evento', max_length=80, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='titulo_slug',
            field=models.SlugField(help_text='Esse campo é o codigo unico da conferencia, não alterar esse campo', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nome_cracha',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome Crachá'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='observacoes',
            field=models.CharField(blank=True, max_length=400, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total Inscrição'),
        ),
    ]
