# Generated by Django 2.2.6 on 2019-12-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191204_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='grau',
            field=models.IntegerField(choices=[(1, 'Conjugue'), (2, 'Filho(a)'), (3, 'Pai/Mãe'), (4, 'Outro')], max_length=30, verbose_name='Grau Parentesco'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='nome_cracha',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome Crachá'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Inscrição'),
        ),
    ]
