# Generated by Django 2.2.6 on 2019-12-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20191218_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='grau',
            field=models.IntegerField(choices=[(1, 'Conjugue'), (2, 'Filho(a)'), (3, 'Pai/Mãe'), (4, 'Outro')], verbose_name='Grau Parentesco'),
        ),
    ]
