# Generated by Django 3.0.3 on 2020-02-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200215_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='hospedagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Hospedagem', verbose_name='Hospedagem'),
        ),
    ]
