# Generated by Django 3.0.3 on 2020-02-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    def corrigir_hospedagem_dependente(apps, schema_editor):
        Inscricao = apps.get_model('data', 'Inscricao')
        Dependente = apps.get_model('data', 'Dependente')
        
        for insc in Inscricao.objects.all():
            for dep in Dependente.objects.filter(inscricao=insc):
                if dep.hospedagem is None:
                    dep.hospedagem = insc.hospedagem
                    dep.save()

    dependencies = [
        ('data', '0004_dependente_hospedagem'),
    ]

    operations = [
        migrations.RunPython(corrigir_hospedagem_dependente),
    ]
