# Generated by Django 2.2.6 on 2019-12-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20191218_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('assunto', models.CharField(max_length=120, verbose_name='Assunto')),
                ('data_contato', models.DateTimeField(auto_now_add=True, verbose_name='Data Contato')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Conferencia', verbose_name='Conferência')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contato',
            },
        ),
    ]
