# Generated by Django 3.0.3 on 2020-02-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200216_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='hospedagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Hospedagem', verbose_name='Hospedagem'),
        ),
    ]
