# Generated by Django 2.2.6 on 2019-12-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20191218_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='endereco',
            field=models.CharField(blank=True, max_length=320, verbose_name='Endereço (googlemaps)'),
        ),
    ]
