# Generated by Django 2.2.6 on 2019-12-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20191218_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='pagseguro_token',
            field=models.CharField(blank=True, max_length=120, verbose_name='Token PagSeguro'),
        ),
    ]
