# Generated by Django 2.2.6 on 2019-12-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_conferencia_pagseguro_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='pagseguro_email',
            field=models.CharField(blank=True, max_length=120, verbose_name='Email PagSeguro'),
        ),
    ]
