# Generated by Django 2.2.6 on 2019-12-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_inscricao_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Referencia Pagamento'),
        ),
    ]
