# Generated by Django 2.2.6 on 2019-12-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20191219_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='pagseguro_email',
        ),
        migrations.RemoveField(
            model_name='conferencia',
            name='pagseguro_token',
        ),
    ]
