# Generated by Django 2.2.6 on 2019-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20191219_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='sit_pagseguro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status PagSeguro'),
        ),
    ]
