# Generated by Django 2.2.6 on 2019-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_inscricao_sit_pagseguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='pagseguro_transaction_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Transação PagSeguro'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Pago'), (3, 'Cancelado'), (4, 'Aguardando Confirmação Pagamento')], default=1, verbose_name='Status'),
        ),
    ]
