# Generated by Django 2.2.6 on 2019-12-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20191219_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='inscricoes_abertas',
            field=models.BooleanField(default=True, verbose_name='Inscrições Abertas?'),
        ),
    ]
