# Generated by Django 3.0.1 on 2019-12-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20191221_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='informacoes_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='informacoes/arquivos/', verbose_name='Arquivo de Informações'),
        ),
    ]
